name: Kusha
favicon: null
layout_spectrum: 0.50422
typography_spectrum: 0.50129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefde'
    - '#4a4231'
    - '#de8452'
    - '#63c5de'
    - '#d6e629'
  brandStrength: 0.5764530894812196
  lightness: 0.3324270297307521
  saturation: 0.5599292910192162
  rhythmicContrast: 0.47186009562574327
purpose: []
