name: Kusha Nikoui - Paychex
favicon: null
layout_spectrum: 0.24202
typography_spectrum: 0.9092
title: Kusha Nikoui - Paychex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe8e0'
    - '#000000'
    - '#3b372e'
    - '#b8c7fe'
    - '#d6834f'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
