name: Kusha Nikoui - Paychex
favicon: null
layout_spectrum: 0.7381
typography_spectrum: 0.55761
title: Kusha Nikoui - Paychex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efe8e0'
    - '#000000'
    - '#3b372e'
    - '#b8c7fe'
    - '#d6834f'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
