name: Kusha
favicon: null
layout_spectrum: 0.65803
typography_spectrum: 1
title: "Kusha's Business Website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3384ca'
    - '#0000ff'
    - '#0055aa'
    - '#0080ff'
    - '#000000'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
